name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: tommybotch/collab-splats:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install repository
        run: |
          cd collab-splats
          bash setup.sh

      - name: Install collab-data
        run: |
          pip install git+https://github.com/BasisResearch/collab-data.git

      - name: Lint
        run: |
          cd collab-splats
          make lint